### ISSUE TITLE
Consider porting from ESPUSB

### ISSUE THREAD

**Issue by cnlohr** [SHA2017-badge/PCB#1]
Just throwing out the idea, though I haven't gotten around to porting ESPUSB to the ESP32, I have considered it.  Any interest in adding possible hardware support to your design?  You would only need to have two adjacent GPIO pins to add support.

**Comment by gavanfantom** [comment]
That's a neat idea but unfortunately we're so close to the event now that we have had to feature-freeze the PCB already.

We do however have quite a lot of software work that needs doing between now and the end of July and while we do have a few people on the team, another person who is as familiar with the ESP32 as you are would be a real advantage. Would you be interested in lending a hand?

**Comment by cnlohr** [comment]
Aah, gotcha.  Things are kinda insane for me, right now since I'm co-chairing MAGStock and that's June 8-11 then I have to worry about badges for MAGLabs (I think they're '8266 because of the stringent price requirements).  I will consider it after MAGStock though.

**Comment by annejan** [comment]
Hi @cnlohr the adjacent IO16 and IO17 pins (as well as IO12, IO14, IO32 (possibly shared with WS2812s), IO33, I2C, 3.3V and GND) are accessible through the badge expansion header :)
So using ESPUSB should be possible as-is . . right?

**Comment by lucysrausch** [comment]
I don't think ESPUSB is ported for the ESP32 yet. Shouldn't be a problem through.

**Comment by cnlohr** [comment]
Hmm, I could see having a connector for it.  Would need a pull-up.  I have really wanted to develop full-speed USB 1.1 for the ESP32 for a while since I think it's possible.

**Comment by van-cahall** [comment]
I'm not familiar with this badge, but ESPUSB for the ESP32 would be awesome!  USB is the only thing missing from the ESP32 for several killer projects I'd like to do.  +1

**Comment by cnlohr** [comment]
Ughhhh.. I'm doing MAGStock prep now.  I think I'm going to put libsurvive on the backburner to give a stab at full-speed USB on the 32.

Low-speed "should" be a trivial change from the '8266.

**Comment by zoutepopcorn** [comment]
Great job cnlohr :D.

**Comment by cnlohr** [comment]
I'm actually doing a totally different approach ATM, but it's going well.  I would much rather get full-speed working over simply switching around low-speed.

**Comment by nissimzur** [comment]
Can someone point me to SHA2017-badge schematics diagram?

**Comment by annejan** [comment]
It's in this repository . .
https://github.com/SHA2017-badge/PCB/blob/master/sha2017_rev1_0_1_schematic.pdf should probably be what you are looking for.

**Comment by nissimzur** [comment]
Thank you.

I offering my help in any hardware challenge you have around ESP8266/ESP32.
