### ISSUE TITLE
DIY badge 

### ISSUE THREAD

**Issue by zoutepopcorn** [SHA2017-badge/PCB#2]
First of all thanks for the amazing SHA Badge and the great work.

It worked perfect on the event, didnt install the ransomeware :P

I wonder where I can order the displays, cant find them on Ali:
DEPG0290

And how the DIY module was made:

![](https://pbs.twimg.com/media/DE2SOTlXgAIspJX.jpg)

**Comment by sebastius** [comment]
The DEPG is difficult to acquire. The GDEH029A1 is easily purchased from AliExpress and relatively cheap too!

https://aliexpress.com/item/2-9-EPD-display-e-paper-display-panel/32218091929.html

This display is hardware compatible (same schematic), just needs a recompile with one setting different (we actually devved on this display so all the software is there!)

**Comment by zoutepopcorn** [comment]
Top thanks
